version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=production
      - DATABASE_URL=sqlite:////app/carrent.db
    depends_on:
      - db

  db:
    image: sqlite:latest
    volumes:
      - ./instance:/app/instance
