services:
  - type: web
    name: car-rent-system
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: car-rent-db
          property: connectionString

databases:
  - name: car-rent-db
    plan: free
    ipAllowList: []  # Allows all IP addresses
