services:
  - type: web
    name: car-rent-system
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        value: 28469767a26613fa0aeb74011cd6f2e97f42ed1ce07c52df48003e14d2b16043
      - key: DATABASE_URL
        value: postgresql://carrent_db_user:Qs9HCnfgZqXkOLVVOyAM5EljQHhtgIyJ@dpg-cujq8et6l47c73c5mk80-a.oregon-postgres.render.com/carrent_db

databases:
  - name: carrent_db
    plan: free
    ipAllowList: []  # Allows all IP addresses
